name: jfxchess
version: "4.3.0"
summary: A graphical chess program
description: |
  JFXChess is a chess graphical user interface
  with the following features:
  * based around world's best chess program Stockfish
  * play against the computer
  * adjust strength levels to match your skill
  * enter, edit and analyse games
  * automatic game analysis
  * read and save games in standard pgn format
  * copy and paste FEN positions and pgn games from clipboard
  * cross-platform, available for Linux and Windows
  * easy and intuitive GUI
confinement: strict
grade: stable
base: core22
architectures:
  - build-on: [amd64]
    build-for: [amd64]

lint:
  ignore:
    - library:
      - usr/lib/jvm/java-*/lib/*.so

apps:
  jfxchess:
    command: usr/bin/jfxchess-snap
    plugs:
      - desktop
      - unity7
      - home
      - cups-control
      - removable-media
    extensions: [gnome]
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-amd64"
      JAVA_TOOL_OPTIONS: "-Duser.home=$SNAP_USER_COMMON"      

parts:
 jfxchess:
    plugin: maven
    source: https://github.com/asdfjkl/jfxchess.git
    maven-parameters: ["clean", "compile", "assembly:single"]
    source-type: git
    build-packages:
      [maven,openjdk-11-jdk]
    stage-packages:
      - openjdk-11-jdk
    organize:
      ${SNAPCRAFT_PART_BUILD}/jfxchess-snap: usr/bin/jfxchess-snap      

 book:
   plugin: dump
   source: snap/local
   stage: 
     - book

 engine:
   plugin: dump
   source: snap/local
   stage: 
     - engine

 splash:
   plugin: dump
   source: snap/local
   stage:
     - splash
