name: jerry
version: "4.0.0"
summary: A graphical chess program
description: |
  Jerry - Das Schachprogramm is a chess graphical user interface
  with the following features:
  * based around world's best chess program Stockfish (as of Jan, 2014)
  * play against the computer
  * adjust strength levels to match your skill
  * enter, edit and analyse games
  * automatic game analysis
  * read and save games in standard pgn format
  * copy and paste FEN positions and pgn games from clipboard
  * cross-platform, available for Linux and Windows
  * easy and intuitive GUI
confinement: devmode
grade: stable
base: core18

apps:
  jerry:
    command: usr/bin/jerry-snap
    plugs:
      - desktop
      - unity7
      - home
      - network
      - cups-control
    extensions: [gnome-3-28]
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-amd64"
      JAVA_TOOL_OPTIONS: "-Duser.home=$SNAP_USER_COMMON"

parts:
 jerry:
    plugin: maven
    source: https://github.com/asdfjkl/jerry.git
    maven-options: ["clean", "compile", "assembly:single"]
    source-type: git
    build-packages:
      - openjdk-11-jdk
    stage-packages:
      - openjdk-11-jdk
    organize:
      ${SNAPCRAFT_PART_BUILD}/jerry-snap: usr/bin/jerry-snap

 book:
   plugin: dump
   source: snap/local
   stage: 
     - book

 engine:
   plugin: dump
   source: snap/local
   stage: 
     - engine

 splash:
   plugin: dump
   source: snap/local
   stage:
     - splash
